# Generated by Django 3.2 on 2021-04-16 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ToDo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название заметки')),
                ('text', models.TextField(verbose_name='Текст заметки')),
                ('image', models.ImageField(blank=True, null=True, upload_to='todo_images/', verbose_name='Картинка')),
                ('color', models.CharField(choices=[('Blue', 'Голубой'), ('Pink', 'Розовый'), ('Yellow', 'Желтый')], max_length=20, verbose_name='Цвет')),
                ('date_time', models.DateTimeField(auto_now=True, verbose_name='Дата')),
            ],
            options={
                'verbose_name': ['Заметка'],
                'verbose_name_plural': ['Заметки'],
            },
        ),
    ]
