# Generated by Django 3.2 on 2021-04-17 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todo',
            options={'verbose_name': 'Заметка', 'verbose_name_plural': 'Заметки'},
        ),
        migrations.AlterField(
            model_name='todo',
            name='color',
            field=models.CharField(blank=True, choices=[('Blue', 'Голубой'), ('Pink', 'Розовый'), ('Yellow', 'Желтый')], max_length=20, null=True, verbose_name='Цвет'),
        ),
    ]
