# Generated by Django 3.2 on 2021-04-18 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0002_auto_20210418_0248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='color',
            field=models.CharField(blank=True, choices=[('Blue', 'Голубой'), ('Pink', 'Розовый'), ('Yellow', 'Желтый'), ('default', '#304B5F')], default='default', max_length=20, null=True, verbose_name='Цвет'),
        ),
    ]
